### ISSUE TITLE
Error: unknown dataset datasets/test.txt

### ISSUE THREAD

**Issue by qq542288564** [almazan/deep-image-retrieval#10]
Error: unknown dataset datasets/test.txt
Available datasets: Dataset, ImageClusters, ImageList, ImageListLabels, ImageListLabelsQ, ImageListROIs, ImageListRelevants, ImagesAndLabels, LabelledDataset, Landmarks18, Landmarks18_5K, Landmarks18_index, Landmarks18_lite, Landmarks18_mid, Landmarks18_missing_index, Landmarks18_new_index, Landmarks18_pca, Landmarks18_test, Landmarks18_train, Landmarks18_val, Landmarks18_valdstr, Landmarks_clean, Landmarks_clean_val, Landmarks_lite, NullCluster, Oxford5K, Paris6K, ROxford5K, RParis6K

 executive command:
python -m dirtorch.extract_features --dataset 'ImageList("test.txt", ["/data01/gtr/studyPytorch/ytst/deep-image-retrieval/datasets"])' --checkpoint /data01/gtr/studyPytorch/ytst/deep-image-retrieval/Resnet101-AP-GeM-LM18.pt --output rparis6k_features.npy --whiten Landmarks_clean --whitenp 0.25 --gpu -1

The picture uses my own picture to generate the feature code. Why is the data invalid

**Comment by TengFei75882341** [comment]
@qq542288564 Hi ，has this problem been solved，ths

**Comment by almazan** [comment]
Hi @qq542288564,

I'm sorry, but I couldn't reproduce this error. I just run again this command in my own set of images and it worked. Could you try again by removing the brackets around the path of your images? It should be something like this:

```
--dataset 'ImageList("test.txt", "/data01/gtr/studyPytorch/ytst/deep-image-retrieval/datasets")'
```

Also, take into account that the path to `test.txt` should be either absolute or relative to the path where you're executing this code (ie. not relative to `/data01/gtr/studyPytorch/ytst/deep-image-retrieval/datasets`).

Hope this helped.
