### ISSUE TITLE
senet miss

### ISSUE THREAD

**Issue by SHIsue** [almazan/deep-image-retrieval#12]
Hi Mr.Almazán,
It seems miss the senet.py when I trying to run the code.
==================================== ERRORS 
_________________________ ERROR collecting test_dir.py _________________________
ImportError while importing test module '/home/sherry/Documents/github_code/deep-image-retrieval-master/dirtorch/test_dir.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../anaconda3/lib/python3.7/site-packages/_pytest/python.py:498: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
../../../../anaconda3/lib/python3.7/site-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
../../../../anaconda3/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:149: in exec_module
    exec(co, module.__dict__)
test_dir.py:16: in <module>
    import dirtorch.nets as nets
nets/__init__.py:94: in <module>
    from .rmac_senet import senet154_rmac, se_resnet50_rmac, se_resnet101_rmac, se_resnet152_rmac, se_resnext50_32x4d_rmac, se_resnext101_32x4d_rmac
nets/rmac_senet.py:2: in <module>
    from .backbones.senet import *

E   ModuleNotFoundError: No module named 'dirtorch.nets.backbones.senet'

!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.42 seconds ============================

**Comment by almazan** [comment]
Hi @SHIsue,

Thanks a lot for noticing and reporting this error. Apparently after cleaning the code I broke a couple of things :sweat_smile:

Just pushed a fix that should address this problem. It should work now, but please let me know if you still have problems running it.

Jon
