### ISSUE TITLE
Supplementary material from the paper

### ISSUE THREAD

**Issue by fede-vaccaro** [almazan/deep-image-retrieval#17]
Hi,
I was trying to use your implementation of the AP-Loss and to replicate your training procedure. In your paper, some supplementary material (with the pseudocode of the multistaged training) is referenced, but I can't find it anywhere. Can you help me with this?

Best Regards,
Federico

**Comment by Skydes** [comment]
The supplementary is in the conference proceedings: http://openaccess.thecvf.com/content_ICCV_2019/supplemental/Revaud_Learning_With_Average_ICCV_2019_supplemental.pdf
