### ISSUE TITLE
When I'm implementing multi-staged backpropagation, output of model's backward method is not working.

### ISSUE THREAD

**Issue by ByungSun12** [almazan/deep-image-retrieval#19]
In dirtorch/nets, These are problems when implementing multi-staged backpropagation.

1) rmac_resnet_fpn.py
2) rmac_resnet.py
3) rmac_resnext.py

For example, at line 64 in 1) `rmac_resnet.py`, original code is below

```python
        x.squeeze_()
```

But this have problem that inplace operation cannot work when calculating gradient descriptor w.r.t. model's parameters.

So, I suggest this code below,

```python
        x = x.squeeze() # This is not in-place operatoration.
```

As above example, 2) and 3) have same problem.

**Comment by 15122901359** [comment]
We could have added a WeChat @ByungSun12 ，I have the same problem.
my WeChat ID:18810270920

**Comment by ByungSun12** [comment]
> We could have added a WeChat @ByungSun12 ，I have the same problem.
> my WeChat ID:18810270920

I request friend in wechat.

**Comment by ByungSun12** [comment]
closed.
