### ISSUE TITLE
mAP comparison on other datasets

### ISSUE THREAD

**Issue by Paul0M** [almazan/deep-image-retrieval#2]
First, great work!
Could you please post a comparison on other datasets.
Such as **CUB** with **Learning with Average Precision: Training Image Retrieval with a Listwise Loss** and **Sampling matters in deep embedding learning**

**Comment by almazan** [comment]
I agree that it would be great to add support to other datasets such as CUB or Stanford Cars, so we might consider this in the near future.

In the meantime, you can use the script `feature_extractor.py` to extract representations from the images in CUB and use them to compute similarities, rankings, and standard metrics. Although the model was trained exclusively on landmarks, we have seen it generalises quite well to other domains.
