### ISSUE TITLE
Could you explain the flip in extract_image_features

### ISSUE THREAD

**Issue by GabbySuwichaya** [almazan/deep-image-retrieval#23]
Hello. Thank you very much for releasing the scripts and sharing your great work. The performance of your work is very impressive. 

As I tried to follow through the usage of your work,  I stumped upon the setting of **flip** in extract_image_features ([Line 47](https://github.com/almazan/deep-image-retrieval/blob/master/dirtorch/test_dir.py#L47) )... 

Could you please help explain what is the function of flip in extract_image_features?  Is it flipping the left and right?   Also, it would be nice if you would explain how to assign this variable ?...

**Comment by almazan** [comment]
Hi @GabbySuwichaya,

First of all, thanks for your nice words and apologies for the lack of documentation in this function. 

The function `extract_image_features` receives as an optional parameter a list of boolean values that indicates wether the image should be flipped or not before extracting features. This is a horizontal flip (left to right), and the length of this list should be equal to the number of images in the dataset. 

This is used for data augmentation, not only at training time, but also at test time. For example, you can extract both representations per image (with and without flip) and average them, which in some cases might bring nice improvements. You could even add vertical flipping if that makes sense for your particular task.

Eventually, you can also replace [line 71](https://github.com/almazan/deep-image-retrieval/blob/366825756909941d99cb7ece9fef5bcb56da6756/dirtorch/test_dir.py#L71) with `if flip:` and then use `flip` as a flag to activate or deactivate flipping. In this case, if you want to activate data augmentation you would call this function twice with `flip=False` and `flip=True` and average the outputs.

I hope this answered your question.

**Comment by GabbySuwichaya** [comment]
@almazan  Thank you so much for the information. Yes, I can see the use of the flip mode now.
