### ISSUE TITLE
Feature extractor error

### ISSUE THREAD

**Issue by VPRzhou** [almazan/deep-image-retrieval#6]
Hi,great work you did.But I have a running problem when I do the feature_extractor.py.
Looking forward your reply,thank you.
$ python -m dirtorch.extract_features --dataset 'ImageList("dirtorch/image.txt")' --checkpoint dirtorch/data/Resnet-101-AP-GeM.pt --output ditorch/data/results --whiten Lankmarks_clean --whitenp 0.25 --gpu 0
Launching on GPUs 0
Dataset: Dataset: ImageList
  3 images
  root: ...
/home/zhoul/anaconda3/lib/python3.6/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator PCA from version 0.20.2 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
=> loading checkpoint 'dirtorch/data/Resnet-101-AP-GeM.pt' (current_iter 296)
Traceback (most recent call last):
  File "/home/zhoul/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zhoul/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhoul/deep-image-retrieval/dirtorch/extract_features.py", line 116, in <module>
    net.pca = net.pca[args.whiten]
KeyError: 'Lankmarks_clean'

**Comment by VPRzhou** [comment]
One more question I want to ask you.I have prepared the dataset of 'Paris6k' before I reproduce the rusults .It is because of the speed of downloading the dataset that makes me annoyed.So how can I change the code of test_dir.py to avoid the process of downloading the dataset.Forgive me for being a new programmer.

**Comment by almazan** [comment]
Hi @VPRzhou,

Regarding your first issue, there's a typo in the name of the dataset used for whitening. You should use `--whiten Landmarks_clean`. Please let me know if this doesn't fix your problem.

Regarding your second question, if the dataset is stored under $DB_ROOT/paris6k the downloader will be able to find it and skip the downloading process. Bear in mind that the code is using the ground-truth file provided by Radenovic et al., so you'll have to download it as well (in case you don't have it already) and put it under the same directory.

Here's the link: http://cmp.felk.cvut.cz/cnnimageretrieval/data/test/paris6k/gnd_paris6k.pkl

**Comment by VPRzhou** [comment]
Thank you very much.I made a mistake on the spelling of "Landmarks_clean",it works now.My second question is also solved following what you say.
There is a suggestion for you.Changing the model name of"Resnet101-AP-GeM.pt" to "Resnet-101-AP-GeM.pt" in the command line.Mainly because the error will happen.
$ python -m dirtorch.test_dir --dataset RParis6K --checkpoint dirtorch/data/Resnet101-AP-GeM.pt --whiten Landmarks_clean --whitenp 0.25 --gpu 0
Launching on GPUs 0
Test dataset: Dataset: RParis6K
  6322 images, 70 queries
  root: /home/zhoul/deep-image-retrieval/dirtorch/data/datasets/paris6k...
Traceback (most recent call last):
  File "/home/zhoul/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zhoul/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhoul/deep-image-retrieval/dirtorch/test_dir.py", line 241, in <module>
    net = load_model(args.checkpoint, args.iscuda)
  File "/home/zhoul/deep-image-retrieval/dirtorch/test_dir.py", line 189, in load_model
    checkpoint = common.load_checkpoint(path, iscuda)
  File "/home/zhoul/deep-image-retrieval/dirtorch/utils/common.py", line 118, in load_checkpoint
    assert os.path.isfile(filename), "=> no checkpoint found at '%s'" % filename
AssertionError: => no checkpoint found at 'dirtorch/data/Resnet101-AP-GeM.pt'

**Comment by almazan** [comment]
Happy to hear that it worked.

Thanks for the suggestion and for catching the typo. I'll update the Readme.
